// Popular London attractions and areas near King's Cross for hotel targeting
const kingsCrossTargetAreas = [
    'King\'s Cross Station',
    'St. Pancras International',
    'British Library',
    'Camden Market',
    'Granary Square',
    'Regent\'s Canal',
    'Coal Drops Yard',
    'The Foundling Museum',
    'University College London (UCL)',
    'The Francis Crick Institute',
    'Bloomsbury',
    'Camden Town',
    'Caledonian Park',
    'Gagosian Gallery Britannia Street',
    'The British Museum',
    'British Museum',
    'Covent Garden',
    'Leicester Square',
    'Piccadilly Circus',
    'Trafalgar Square',
    'Oxford Street',
    'Regent Street',
    'Bond Street',
    'Carnaby Street',
    'Soho',
    'Chinatown',
    'West End Theatre District',
    'London Zoo',
    'Regent\'s Park',
    'Primrose Hill',
    'Hyde Park',
    'Kensington Gardens',
    'The Shard',
    'Tower Bridge',
    'Tower of London',
    'St. Paul\'s Cathedral',
    'Tate Modern',
    'Shakespeare\'s Globe',
    'Southbank Centre',
    'London Eye',
    'Buckingham Palace',
    'Westminster Abbey',
    'Houses of Parliament',
    'Big Ben',
    'Tate Britain',
    'Natural History Museum',
    'Science Museum',
    'Victoria and Albert Museum',
    'Royal Albert Hall',
    'Chelsea',
    'Kensington',
    'Notting Hill',
    'Portobello Road Market',
    'Royal Opera House',
    'Royal Courts of Justice',
    'Somerset House',
    'Covent Garden Market',
  ];
  
  export default kingsCrossTargetAreas;
  