// Popular London attractions and areas near King's Cross for hotel targeting
const kingsCrosssurroundingreas = [
    'Alexandra Palace',
  'Angel',
  'Archway',
  'Balham',
  'Bankside',
  'Barnsbury',
  'Bermondsey',
  'Bethnal Green',
  'Bloomsbury',
  'Borough',
  'Bow',
  'Brixton',
  'Camden',
  'Canonbury',
  'Clerkenwell',
  'Clapham',
  'Covent Garden',
  'Crouch End',
  'Dalston',
  'De Beauvoir Town',
  'Dartmouth Park',
  'Elephant and Castle',
  'Euston',
  'Farringdon',
  'Finsbury',
  'Fitzrovia',
  'Hackney',
  'Hackney Wick',
  'Haggerston',
  'Highbury',
  'Highgate',
  'Holborn',
  'Holloway',
  'Homerton',
  'Hornsey',
  'Hoxton',
  'Islington',
  'Kennington',
  'Lambeth',
  'London Bridge',
  'Manor House',
  'Marylebone',
  'Mile End',
  'Muswell Hill',
  'Newington Green',
  'Pentonville',
  'Putney',
  'Regent\'s Park',
  'Rotherhithe',
  'Seven Sisters',
  'Shoreditch',
  'Soho',
  'South Bank',
  'Southwark',
  'Spitalfields',
  'Stamford Hill',
  'Stepney',
  'Stockwell',
  'Stoke Newington',
  'Stroud Green',
  'Tottenham',
  'Tooting',
  'Tufnell Park',
  'Vauxhall',
  'Victoria Park',
  'Walthamstow',
  'Wandsworth',
  'Wapping',
  'Waterloo',
  'Whitechapel',
  'Wood Green',
  ];
  
  export default kingsCrosssurroundingreas;
  